server:
  port: 8192
#数据源
spring:
  # 数据库链接配置
  datasource:
    url: jdbc:mysql://47.76.67.144:3306/animals?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000
#上传
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  #邮箱
  data:
    mongodb:
      uri: mongodb://localhost:27017/com
  mail:
    host: smtp.qq.com
    username: 3328397500@qq.com
    password: bbyhlaokcznsdaff
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  redis:
    database: 0
    host: 192.168.200.204
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1ms
        max-active: 1000
        max-idle: 16
        min-idle: 8
  rabbitmq:
    addresses: rabbitmq-server
    username: mldnjava
    password: hello
    virtual-host: /
# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper*xml
  type-aliases-package: com.scy.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



#日志
logging:
  level:
    root: info
    com.scy.dao: warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"


Animal:
  jwt:
    secret: "12312"
    expire: 5
    cache-expire: 1000

#支付
wechatpay:
  mchId: YourMchId
  apiSecret: YourApiSecret
  certPath: /path/to/your/apiclient_cert.p12
  certPassword: xvgcvvdvkviwhvoevpwup

qiniu:
  kodo:
    # 配置accessKey
    accessKey: oGONCQtRfbLCdWHb1VeOUPLp8Og4P3J-q80RjiIC
    # 配置secretKey
    secretKey: bZ8OtQY_FzGN2_9oMnuedpkE4HaGqx1zdtIKh-b1
    # 配置空间名称
    bucket: miansdd
    # 配置域名
    domain: siznph170.hd-bkt.clouddn.com

minio:
  endpoint: http://192.168.200.204:9001 #Minio服务所在地址
  bucketName: comic #存储桶名称
  accessKey: 3nWUpakF5zMizadCAuca #访问的key
  secretKey: ao0kiNnoeNgnXEgze0fdl09a05YPn8TY9aLKjBoI #访问的秘钥
